#!/bin/bash
# -*- coding: utf-8 -*-
# Copyright (c) 2014, Sven Kretschmann
# All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
if [ "--help" = "$1" ]
then
    echo "Display the changes for a given target."
    echo
    echo "Usage: $0 -r'revisions' <target>"
    echo
    echo "All parameters are optional."
    echo "-r The revisions to the display the changes for (e.g 4:7)"
    echo "-e Preg Pattern defining the file names / paths to be exluded from the display."
    echo "-nc No color: Do not colorize the changes."
    exit 0
fi

source `dirname $0`/conf/env.sh

$PHP_COMMAND $BIN_DIR/helpers/diff.php $*
