#!/bin/bash
# -*- coding: utf-8 -*-
# Copyright (c) 2014, Sven Kretschmann
# All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
if [ "--help" = "$1" ]
then
    echo "Display the subversin log for a given target."
    echo
    echo "Usage: $0 -n# -r'revision' -s'search' <target>"
    echo
    echo "All parameters are optional."
    echo "-n The number of lines per log message"
    echo "-r The revision range (e.g. 1-5,7)"
    echo "-s The search pattern to filter the log entries with"
    exit 0
fi

source `dirname $0`/conf/env.sh

$PHP_COMMAND $BIN_DIR/helpers/_log.php $*
